**MATRIX ADITION**

In [ ]:
import numpy as np
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
C = A + B

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A + B =\n", C)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
A + B =
 [[ 6  8]
 [10 12]]
