**MATRIX INVERSE**

In [ ]:
import numpy as np
A = np.array([[4, 7],
              [2, 6]])
A_inv = np.linalg.inv(A)

print("Matrix A:")
print(A)
print("\nInverse of A:")
print(A_inv)
identity = np.dot(A, A_inv)
print("\nA x A_inv (should be identity matrix):")
print(identity)


Matrix A:
[[4 7]
 [2 6]]

Inverse of A:
[[ 0.6 -0.7]
 [-0.2  0.4]]

A x A_inv (should be identity matrix):
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
