**MATRIX MULTIPLICATION**

In [1]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
C = np.dot(A, B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A x B =\n", C)


Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[ 7  8]
 [ 9 10]
 [11 12]]
A x B =
 [[ 58  64]
 [139 154]]
